#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Pyro-ManUserbot
#
# This file is a part of < https://github.com/mrismanaziz/PyroMan-Userbot/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/mrismanaziz/PyroMan-Userbot/blob/main/LICENSE/>.
#
# t.me/SharingUserbot & t.me/Lunatic0de

_starter () {
    echo "Downloading source code"
    git clone https://github.com/mrismanaziz/PyroMan-Userbot
    cd PyroMan-Userbot/
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "Pyroman-Userbot v${BOT_VER}, Copyright © 2022 (Risman) <https://github.com/mrismanaziz>"
    python3 -m ProjectMan
}

_starter
